In [1]:
# 라이브러리
import tensorflow as tf
import pandas as pd

# 보스턴 집값 예측


In [2]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

In [3]:
# 종속변수, 독립변수
독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 
            'rm', 'age', 'dis', 'rad', 'tax',
            'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [4]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[13])
H = tf.keras.layers.Dense(10, activation='swish')(X)
H = tf.keras.layers.Dense(10, activation='swish')(H)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [5]:
# 모델 구조 확인
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense (Dense)                (None, 10)                140       
_________________________________________________________________
dense_1 (Dense)              (None, 10)                110       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 11        
Total params: 261
Trainable params: 261
Non-trainable params: 0
_________________________________________________________________


In [6]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
16/16 [==============================] - 1s 2ms/step - loss: 1269.2358
Epoch 2/100
16/16 [==============================] - 0s 2ms/step - loss: 498.9000
Epoch 3/100
16/16 [==============================] - 0s 2ms/step - loss: 383.4967
Epoch 4/100
16/16 [==============================] - 0s 2ms/step - loss: 172.3361
Epoch 5/100
16/16 [==============================] - 0s 2ms/step - loss: 142.0627
Epoch 6/100
16/16 [==============================] - 0s 2ms/step - loss: 111.0895
Epoch 7/100
16/16 [==============================] - 0s 2ms/step - loss: 75.8604
Epoch 8/100
16/16 [==============================] - 0s 2ms/step - loss: 71.3322
Epoch 9/100
16/16 [==============================] - 0s 2ms/step - loss: 65.7737
Epoch 10/100
16/16 [==============================] - 0s 2ms/step - loss: 55.3673
Epoch 11/100
16/16 [==============================] - 0s 2ms/step - loss: 58.1029
Epoch 12/100
16/16 [==============================] - 0s 2ms/step - loss: 57.3717
Epoch 13/100
16/16

In [7]:
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[32.688137]
 [28.96907 ]
 [31.91101 ]
 [32.1479  ]
 [31.005419]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


# 아이리스 품종 분류

In [8]:
# 1.과거의 데이터를 준비합니다.
파일경로 = 'https://raw.githubusercontent.com/blackdew/tensorflow1/master/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

In [9]:
# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)

In [10]:
# 종속변수, 독립변수
독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]
print(독립.shape, 종속.shape)

(150, 4) (150, 3)


In [11]:
# 2. 모델의 구조를 만듭니다
X = tf.keras.layers.Input(shape=[4])
H = tf.keras.layers.Dense(8, activation="swish")(X)
H = tf.keras.layers.Dense(8, activation="swish")(H)
H = tf.keras.layers.Dense(8, activation="swish")(H)
Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy',
              metrics='accuracy')

In [12]:
# 모델 구조 확인
model.summary()

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_3 (Dense)              (None, 8)                 40        
_________________________________________________________________
dense_4 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_5 (Dense)              (None, 8)                 72        
_________________________________________________________________
dense_6 (Dense)              (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


In [13]:
# 3.데이터로 모델을 학습(FIT)합니다.
model.fit(독립, 종속, epochs=100)

Epoch 1/100
5/5 [==============================] - 1s 4ms/step - loss: 0.8080 - accuracy: 0.8413
Epoch 2/100
5/5 [==============================] - 0s 3ms/step - loss: 0.7153 - accuracy: 0.7957
Epoch 3/100
5/5 [==============================] - 0s 2ms/step - loss: 0.6768 - accuracy: 0.7604
Epoch 4/100
5/5 [==============================] - 0s 2ms/step - loss: 0.6223 - accuracy: 0.8134
Epoch 5/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5808 - accuracy: 0.8591
Epoch 6/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5392 - accuracy: 0.8736
Epoch 7/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5195 - accuracy: 0.8648
Epoch 8/100
5/5 [==============================] - 0s 2ms/step - loss: 0.5024 - accuracy: 0.8958
Epoch 9/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4725 - accuracy: 0.8906
Epoch 10/100
5/5 [==============================] - 0s 2ms/step - loss: 0.4520 - accuracy: 0.8942
Epoch 11/100
5/5 [===========

In [14]:
# 4. 모델을 이용합니다
print(model.predict(독립[:5]))
print(종속[:5])

[[9.9994433e-01 5.5724799e-05 5.0819982e-13]
 [9.9971551e-01 2.8443034e-04 9.5594444e-12]
 [9.9984920e-01 1.5078550e-04 5.7375246e-12]
 [9.9953640e-01 4.6367972e-04 4.2823012e-11]
 [9.9995112e-01 4.8888356e-05 5.2837926e-13]]
   품종_setosa  품종_versicolor  품종_virginica
0          1              0             0
1          1              0             0
2          1              0             0
3          1              0             0
4          1              0             0
